# Autostart — procesos que arrancan con Hyprland

# Polkit agent — autenticacion grafica (sudo en GUI)
exec-once = /usr/libexec/hyprpolkitagent

# Portal XDG — necesario para apps Wayland/Flatpak
exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/xdg-desktop-portal &

# Wallpaper daemon (swww)
exec-once = swww-daemon
exec-once = sleep 1 && [[ -f $HOME/.local/share/wallpapers/wallpaper.jpg ]] && swww img $HOME/.local/share/wallpapers/wallpaper.jpg --transition-type fade --transition-duration 1

# Notificaciones
exec-once = dunst

# Barra de estado
exec-once = waybar

# Nombres de workspaces (aplica en cada arranque)
exec-once = hyprctl dispatch renameworkspace 1 term
exec-once = hyprctl dispatch renameworkspace 2 code
exec-once = hyprctl dispatch renameworkspace 3 web
exec-once = hyprctl dispatch renameworkspace 4 db
exec-once = hyprctl dispatch renameworkspace 5 media
exec-once = hyprctl dispatch renameworkspace 6 misc
