# Autostart — procesos que arrancan con Hyprland

# Portal XDG — necesario para apps Wayland/Flatpak
exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/xdg-desktop-portal &

# Wallpaper daemon (swww)
exec-once = swww-daemon

# Notificaciones
# exec-once = dunst   # descomentar cuando exista dunstrc

# Barra de estado
exec-once = waybar
