# Autostart — procesos que arrancan con Hyprland

# Polkit agent — autenticacion grafica (sudo en GUI)
exec-once = /usr/libexec/hyprpolkitagent

# Portal XDG — necesario para apps Wayland/Flatpak
exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/xdg-desktop-portal &

# Wallpaper daemon (swww)
exec-once = swww-daemon
exec-once = sleep 1 && [[ -f $HOME/.local/share/wallpapers/wallpaper.jpg ]] && swww img $HOME/.local/share/wallpapers/wallpaper.jpg --transition-type fade --transition-duration 1

# Notificaciones
exec-once = dunst

# Barra de estado
exec-once = waybar
