# Configuracion general de ventanas y espacios de trabajo

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(cba6f7ff) rgba(89b4faff) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    resize_on_border = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
