# Configuracion general de ventanas y espacios de trabajo

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $accent $accent_alt 45deg
    col.inactive_border = $surface0
    layout = dwindle
    resize_on_border = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
