# Reglas de ventanas por aplicacion

# Thunar — flotante
windowrule {
    name = thunar-float
    match:class = thunar
    float = yes
    size = 900 600
    center = yes
}

# Dialogs flotantes
windowrule {
    name = dialog-open-float
    match:title = Open File.*
    float = yes
}

windowrule {
    name = dialog-save-float
    match:title = Save File.*
    float = yes
}

windowrule {
    name = dialog-confirm-float
    match:title = Confirm.*
    float = yes
}
