# Reglas de ventanas por aplicacion

# Thunar — flotante
windowrulev2 = float, class:^(thunar)$
windowrulev2 = size 900 600, class:^(thunar)$
windowrulev2 = center, class:^(thunar)$

# Dialogs flotantes
windowrulev2 = float, title:^(Open File)(.*)$
windowrulev2 = float, title:^(Save File)(.*)$
windowrulev2 = float, title:^(Confirm)(.*)$
