# Workspaces nombrados — persistentes para que Waybar los muestre siempre

workspace = 1, name:term,    persistent:true
workspace = 2, name:code,    persistent:true
workspace = 3, name:web,     persistent:true
workspace = 4, name:db,      persistent:true
workspace = 5, name:media,   persistent:true
workspace = 6, name:misc,    persistent:true
