# hyprland.conf — punto de entrada
# No poner config aqui directamente — solo source de sub-configs

source = ~/.config/hypr/themes/current.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/autostart.conf

